apiVersion: v1
kind: Namespace
metadata:
  name: kube-sec
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-sec
  namespace: kube-sec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-sec-read-only
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-sec-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-sec-read-only
subjects:
  - kind: ServiceAccount
    name: kube-sec
    namespace: kube-sec
---
# Token Secret for the SA (for K8s v1.24+)
apiVersion: v1
kind: Secret
metadata:
  name: kube-sec-token
  namespace: kube-sec
  annotations:
    kubernetes.io/service-account.name: kube-sec
type: kubernetes.io/service-account-token
